### ISSUE TITLE
Data synchronization mechanism

### ISSUE THREAD

**Issue by yshalenyk** [open-contracting/api-specification#10]
Keeping data locally is a sane choice while making analysys over published data.
But  now api specification don't describe a way of syncing data to working storage except dump all the data every time, which is overkill in most cases.

In openprocurement we have a pagination mechanism which helps to define modified tenders by dateModified field. Then scrips just walk over every page and retrieve only changed data. Maybe api should provide something similar?

**Comment by timgdavies** [comment]
Agreed this would be good for us to specify as part of expanded API spec.

**Comment by mireille-raad** [comment]
The problem with sorting the data by date modified and using paging is that it doesn't really enable real time.
People would create scripts and run them at different intervals to get new data. If you are using API to really integrate different systems (as a real interface between application), it might be tricky to tell a person to wait for the next day to see when something is approved for example because data needs to synchronize.

I am looking at building an API, for implementation i am investigating the use of:

- HTTP Streaming (think like twitter API)
- Web hooks which basically use HTTP POST to a callback when certain things happen. You can use this as a "subscription system" to data. Different systems can use different "hooks"
- Polling:
         - Regular Polling (which is close to what you are doing)
         - Long Polling

I am still doing my research ... so any further ideas or suggestions to look into would be useful.

I will share research/finding here once done.

**Comment by jpmckinney** [comment]
Closing as additional work on a standard API specification isn't anticipated in the near future, though the options discussed are all good practices (and not specific to OCDS).
