### ISSUE TITLE
Packaging, the API extension and data from multiple publishers

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/api-specification#15]
Currently the API specification is unclear on whether responses from all endpoints should be served in a package. 

From discussion with @kindly and @pindec we think all responses should be wrapped in a release package, to provide consistency for users and tool developers and because existing tools are designed to accept packaged data.

PR #14 updates `ocds_api_specification.json` to clarify that the `release.json` and `record.json` endpoints should be served in a package and amends `README.md` to caveat the use of the API extension (which removes metadata from the package and embeds it in the release) to APIs which serve data from multiple publishers.

Embedding the package metadata in the release is only necessary and desirable when the API contains data from multiple publishers, whereas providing a `links` object for pagination is desirable for any API returning multiple responses, so I propose splitting the API extension as follows:

1. API pagination extension
Extension which adds the `links` object to the package metadata for release and record packages. This SHOULD be used for any API endpoints which return multiple releases or records. @odscjames also suggested adding an additional `count` property to the `links` object to provide the total number of releases or records.

2. API multiple publisher extension
Extension which embeds the package metadata in the release object. This SHOULD be used for any API endpoints which return multiple releases or records AND contain data from multiple publishers.

@kindly suggested we could consider an alternative approach for the multiple publisher scenario of returning a list of release packages, rather than embedding the package metadata, however I think for consistency (i.e. everything is served in a release or record package) that embedding is preferable.

@jpmckinney, @kindly, @odscjames, @pindec what do you think?

If we have consensus I can draft up the changes and submit a PR.

**Comment by jpmckinney** [comment]
Which package metadata specifically?

* `uri`: I don't think we should be putting the `uri` of the package in the release, as a release can be included in any number of packages.
* `publishedDate`: Same reason as for `uri`, plus release has its own `date`
* `publicationPolicy`: It seems an overreach for data to declare the URL of the policy for its own publication, especially as this URL can change over time – and publishers shouldn't have to publish a new release to update it. It's fine in the package, as packages aren't immutable. I'm not sure what the guidance should be if different publishers have different policies, however. It wouldn't be too consequential to omit this, as it should be discoverable in non-machine-readable format.
* `license`: Same reason as for `publicationPolicy`. Presumably, the combined package will use a license that is either compatible with those of the publishers, or agreed to by the publishers.
* `extensions`: This is needed to interpret the data, but no tool expects to find it on the release. If different publishers use different extensions, the combined package should merge the lists of extensions together.
* `version`: Same caveat as for `extensions`, but the solution is different. Thankfully, 1.1 is backwards compatible with 1.0, so the rule can be that the combined package says it's 1.1. If there are any 1.0 releases in the package, they'll just produce deprecation warnings.

So, I think we're just talking about `publisher`. I have some concerns about it (same as those for `publicationPolicy`); in general, mixing metadata with data challenges the design of immutable releases. Some alternatives to overcome the challenge would be:

* avoid mixing metadata with data: for example, the package replaces `publisher` with a `publishers` array; each item contains a list of OCID-release ID pairs published by that publisher
* make the metadata more immutable: for example, publishers are assigned a non-semantic identifier, which is added to the release – rather than their name and URL, which does change

Note that there are some issues on `standard` about multiple publishers for one contracting process.

----

More broadly:

1. Any extensions to serve API publication should make sense when used outside the context of an API. We don't want to end up in a situation where (a) data output from an API is not interoperable with data output from a bulk download (e.g. if we were to move `extensions`), (b) releases are immutable in one context but not in another or (c) data input to an API requires different considerations than data input to a bulk download (e.g. if publishers were to have to make new releases to update licenses, etc.)

2. We shouldn't expend much effort on the API specification, particularly on aspects that are API-specific. Handling multiple publishers isn't API-specific, and can even be discussed on the main `standard` repo; same with ensuring the use of packages #14. On the other hand, deciding whether to include a `count` field or support GraphQL queries #12, etc. is API-specific. There are tons of resources out there to help people design APIs; there aren't many to help people design contracting data. We need to focus our efforts on the latter, which is why I closed all the issues in this repo (with explanations to the issue authors).

**Comment by jpmckinney** [comment]
Closing in favor of https://github.com/open-contracting/standard/issues/325
