### ISSUE TITLE
Shall we use Spore format or OpenAPI for specifying the JSON API.

### ISSUE THREAD

**Issue by des2013** [open-contracting/api-specification#2]
How does this standard mesh with OpenAPI?  OpenAPI is the recently opened Swagger spec, which is the world's most popular API development and documentation platform. (see also http://civdat.us/standards/index.html)

**Comment by kindly** [comment]
We began with the [Spore](https://github.com/SPORE/specifications/blob/master/spore_description.pod) format (as it was suggested by @myroslav) but we have not finalized this yet.

I have renamed this ticket to a question asking if we should use at using OpenAPI instead. After reading up on OpenAPI I think we should probably change to it, especially as it has lots of tooling already and looks more comprehensive.  The only downside is that is a bit more complicated.

**Comment by des2013** [comment]
Spot on. I was hesitant to suggest it for that exact reason. There are several other (and simpler) alternatives, but none with a documented market share or wider acceptance than OpenAPI. Probably, after the dust settles, there will be several "standard" discovery methods left, OpenApi being one. The Google Discovery API seems to share the complexity of OpenAPI, but perhaps has less enthusiastic support from the user community.

**Comment by andrewlorien** [comment]
Hello from Sydney (although i'm working for Canberra)
We're starting work next month on an API based on the 360Giving API (built for grants rather than contracts, but very similar).  Eventually (hopefully) we'll build a Contracts API based on the same spec.  
I've included jsonapi.org in our documentation, but we're not committed to it.  It's simpler than OpenAPI, but it's particularly missing an authentication section which we'll need.
I've read (well, skimmed) the OpenAPI spec today, and it is pretty comprehensive.  
So if that's where you guys are going, we'll go there too.

**Comment by kindly** [comment]
I have updated the very basics of an API specification using swagger/openAPI and documented that this is the direction we are going in ce32c2945c68cca74168f92 

To view it in a more human readable form you can see it here:
http://editor.swagger.io/#/?import=https://raw.githubusercontent.com/open-contracting/api-specification/master/ocds_api_specification.json

I will close this issue soon if no one has any objections to this change.

**Comment by KrzysztofMadejski** [comment]
just a sidenote to @andrewlorien: jsonapi is an API standard, whereas swagger/openapi is an API documentation standard. For example with OpenAPI you can document jsonapi-compliant API.

+1 for openAPI due to its market share

**Comment by kindly** [comment]
I am going to close this as I think opanAPI has been agreed upon.
